/* Generated by Yosys 0.36+58 (git sha1 ea7818d31, x86_64-w64-mingw32-g++ 13.2.0 -O3 -DNDEBUG) */

module test(clk, rst_l, led);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  input clk;
  wire clk;
  wire \counter[0] ;
  wire \counter[10] ;
  wire \counter[11] ;
  wire \counter[12] ;
  wire \counter[13] ;
  wire \counter[14] ;
  wire \counter[15] ;
  wire \counter[16] ;
  wire \counter[17] ;
  wire \counter[18] ;
  wire \counter[19] ;
  wire \counter[1] ;
  wire \counter[20] ;
  wire \counter[21] ;
  wire \counter[22] ;
  wire \counter[23] ;
  wire \counter[24] ;
  wire \counter[25] ;
  wire \counter[2] ;
  wire \counter[3] ;
  wire \counter[4] ;
  wire \counter[5] ;
  wire \counter[6] ;
  wire \counter[7] ;
  wire \counter[8] ;
  wire \counter[9] ;
  wire \current_led[0] ;
  wire \current_led[1] ;
  wire \current_led[2] ;
  output [7:0] led;
  wire [7:0] led;
  input rst_l;
  wire rst_l;
  xci2_inv _098_ (
    .a(rst_l),
    .y(_026_)
  );
  xci2_and3 _099_ (
    .a(\counter[0] ),
    .b(\counter[2] ),
    .c(\counter[1] ),
    .y(_079_)
  );
  xci2_and3 _100_ (
    .a(\counter[3] ),
    .b(\counter[4] ),
    .c(_079_),
    .y(_080_)
  );
  xci2_and3 _101_ (
    .a(\counter[5] ),
    .b(\counter[6] ),
    .c(_080_),
    .y(_081_)
  );
  xci2_nor3 _102_ (
    .a(\counter[9] ),
    .b(\counter[10] ),
    .c(\counter[11] ),
    .y(_082_)
  );
  xci2_and2ft _103_ (
    .a(\counter[8] ),
    .b(_082_),
    .y(_083_)
  );
  xci2_nand3fft _104_ (
    .a(\counter[7] ),
    .b(_081_),
    .c(_083_),
    .y(_084_)
  );
  xci2_and3 _105_ (
    .a(\counter[13] ),
    .b(\counter[12] ),
    .c(\counter[14] ),
    .y(_085_)
  );
  xci2_and2 _106_ (
    .a(\counter[15] ),
    .b(_085_),
    .y(_086_)
  );
  xci2_ao21 _107_ (
    .a(_084_),
    .b(_086_),
    .c(\counter[16] ),
    .y(_087_)
  );
  xci2_ao21 _108_ (
    .a(\counter[17] ),
    .b(_087_),
    .c(\counter[18] ),
    .y(_088_)
  );
  xci2_and3 _109_ (
    .a(\counter[20] ),
    .b(\counter[23] ),
    .c(\counter[22] ),
    .y(_089_)
  );
  xci2_and3 _110_ (
    .a(\counter[19] ),
    .b(\counter[21] ),
    .c(_089_),
    .y(_090_)
  );
  xci2_ao21 _111_ (
    .a(_088_),
    .b(_090_),
    .c(\counter[24] ),
    .y(_091_)
  );
  xci2_nand2 _112_ (
    .a(\counter[25] ),
    .b(_091_),
    .y(_092_)
  );
  xci2_nor3 _113_ (
    .a(\current_led[0] ),
    .b(\current_led[1] ),
    .c(\current_led[2] ),
    .y(_093_)
  );
  xci2_mux2h _114_ (
    .a(_093_),
    .b(led[0]),
    .s(_092_),
    .y(_027_)
  );
  xci2_and3 _115_ (
    .a(\current_led[0] ),
    .b(\counter[25] ),
    .c(_091_),
    .y(_094_)
  );
  xci2_and3fft _116_ (
    .a(\current_led[1] ),
    .b(\current_led[2] ),
    .c(\current_led[0] ),
    .y(_095_)
  );
  xci2_mux2h _117_ (
    .a(_095_),
    .b(led[1]),
    .s(_092_),
    .y(_028_)
  );
  xci2_and3fft _118_ (
    .a(\current_led[0] ),
    .b(\current_led[2] ),
    .c(\current_led[1] ),
    .y(_096_)
  );
  xci2_mux2h _119_ (
    .a(_096_),
    .b(led[2]),
    .s(_092_),
    .y(_029_)
  );
  xci2_nand2 _120_ (
    .a(\current_led[1] ),
    .b(_094_),
    .y(_097_)
  );
  xci2_and3ftt _121_ (
    .a(\current_led[2] ),
    .b(_094_),
    .c(\current_led[1] ),
    .y(_038_)
  );
  xci2_ao21 _122_ (
    .a(led[3]),
    .b(_092_),
    .c(_038_),
    .y(_030_)
  );
  xci2_and3fft _123_ (
    .a(\current_led[0] ),
    .b(\current_led[1] ),
    .c(\current_led[2] ),
    .y(_039_)
  );
  xci2_mux2h _124_ (
    .a(_039_),
    .b(led[4]),
    .s(_092_),
    .y(_031_)
  );
  xci2_and3ftt _125_ (
    .a(\current_led[1] ),
    .b(\current_led[2] ),
    .c(\current_led[0] ),
    .y(_040_)
  );
  xci2_mux2h _126_ (
    .a(_040_),
    .b(led[5]),
    .s(_092_),
    .y(_032_)
  );
  xci2_and3ftt _127_ (
    .a(\current_led[0] ),
    .b(\current_led[1] ),
    .c(\current_led[2] ),
    .y(_041_)
  );
  xci2_mux2h _128_ (
    .a(_041_),
    .b(led[6]),
    .s(_092_),
    .y(_033_)
  );
  xci2_and3 _129_ (
    .a(\current_led[1] ),
    .b(\current_led[2] ),
    .c(_094_),
    .y(_042_)
  );
  xci2_ao21 _130_ (
    .a(led[7]),
    .b(_092_),
    .c(_042_),
    .y(_034_)
  );
  xci2_xnor2 _131_ (
    .a(\current_led[0] ),
    .b(_092_),
    .y(_035_)
  );
  xci2_xnor2ft _132_ (
    .a(\current_led[1] ),
    .b(_094_),
    .y(_036_)
  );
  xci2_xnor2 _133_ (
    .a(\current_led[2] ),
    .b(_097_),
    .y(_037_)
  );
  xci2_aoi21 _134_ (
    .a(\counter[25] ),
    .b(_091_),
    .c(\counter[0] ),
    .y(_000_)
  );
  xci2_xnor2 _135_ (
    .a(\counter[0] ),
    .b(\counter[1] ),
    .y(_043_)
  );
  xci2_aoi21 _136_ (
    .a(\counter[25] ),
    .b(_091_),
    .c(_043_),
    .y(_011_)
  );
  xci2_ao21 _137_ (
    .a(\counter[0] ),
    .b(\counter[1] ),
    .c(\counter[2] ),
    .y(_044_)
  );
  xci2_and3ftt _138_ (
    .a(_079_),
    .b(_092_),
    .c(_044_),
    .y(_018_)
  );
  xci2_xnor2 _139_ (
    .a(\counter[3] ),
    .b(_079_),
    .y(_045_)
  );
  xci2_aoi21 _140_ (
    .a(\counter[25] ),
    .b(_091_),
    .c(_045_),
    .y(_019_)
  );
  xci2_ao21 _141_ (
    .a(\counter[3] ),
    .b(_079_),
    .c(\counter[4] ),
    .y(_046_)
  );
  xci2_and3ftt _142_ (
    .a(_080_),
    .b(_092_),
    .c(_046_),
    .y(_020_)
  );
  xci2_xnor2 _143_ (
    .a(\counter[5] ),
    .b(_080_),
    .y(_047_)
  );
  xci2_aoi21 _144_ (
    .a(\counter[25] ),
    .b(_091_),
    .c(_047_),
    .y(_021_)
  );
  xci2_ao21 _145_ (
    .a(\counter[5] ),
    .b(_080_),
    .c(\counter[6] ),
    .y(_048_)
  );
  xci2_and3ftt _146_ (
    .a(_081_),
    .b(_092_),
    .c(_048_),
    .y(_022_)
  );
  xci2_xnor2 _147_ (
    .a(\counter[7] ),
    .b(_081_),
    .y(_049_)
  );
  xci2_aoi21 _148_ (
    .a(\counter[25] ),
    .b(_091_),
    .c(_049_),
    .y(_023_)
  );
  xci2_ao21 _149_ (
    .a(\counter[7] ),
    .b(_081_),
    .c(\counter[8] ),
    .y(_050_)
  );
  xci2_and3 _150_ (
    .a(\counter[8] ),
    .b(\counter[7] ),
    .c(_081_),
    .y(_051_)
  );
  xci2_nor3fft _151_ (
    .a(_092_),
    .b(_050_),
    .c(_051_),
    .y(_024_)
  );
  xci2_xnor2 _152_ (
    .a(\counter[9] ),
    .b(_051_),
    .y(_052_)
  );
  xci2_aoi21 _153_ (
    .a(\counter[25] ),
    .b(_091_),
    .c(_052_),
    .y(_025_)
  );
  xci2_ao21 _154_ (
    .a(\counter[9] ),
    .b(_051_),
    .c(\counter[10] ),
    .y(_053_)
  );
  xci2_and3 _155_ (
    .a(\counter[9] ),
    .b(\counter[10] ),
    .c(_051_),
    .y(_054_)
  );
  xci2_nor3fft _156_ (
    .a(_092_),
    .b(_053_),
    .c(_054_),
    .y(_001_)
  );
  xci2_and2 _157_ (
    .a(\counter[11] ),
    .b(_054_),
    .y(_055_)
  );
  xci2_xnor2 _158_ (
    .a(\counter[11] ),
    .b(_054_),
    .y(_056_)
  );
  xci2_aoi21 _159_ (
    .a(\counter[25] ),
    .b(_091_),
    .c(_056_),
    .y(_002_)
  );
  xci2_xnor2 _160_ (
    .a(\counter[12] ),
    .b(_055_),
    .y(_057_)
  );
  xci2_aoi21 _161_ (
    .a(\counter[25] ),
    .b(_091_),
    .c(_057_),
    .y(_003_)
  );
  xci2_ao21 _162_ (
    .a(\counter[12] ),
    .b(_055_),
    .c(\counter[13] ),
    .y(_058_)
  );
  xci2_nand3 _163_ (
    .a(\counter[13] ),
    .b(\counter[12] ),
    .c(_055_),
    .y(_059_)
  );
  xci2_and3 _164_ (
    .a(_092_),
    .b(_058_),
    .c(_059_),
    .y(_004_)
  );
  xci2_and3 _165_ (
    .a(\counter[11] ),
    .b(_085_),
    .c(_054_),
    .y(_060_)
  );
  xci2_ao21ftt _166_ (
    .a(\counter[14] ),
    .b(_059_),
    .c(_060_),
    .y(_061_)
  );
  xci2_aoi21 _167_ (
    .a(\counter[25] ),
    .b(_091_),
    .c(_061_),
    .y(_005_)
  );
  xci2_oai21 _168_ (
    .a(\counter[15] ),
    .b(_060_),
    .c(_092_),
    .y(_062_)
  );
  xci2_aoi21 _169_ (
    .a(\counter[15] ),
    .b(_060_),
    .c(_062_),
    .y(_006_)
  );
  xci2_ao21 _170_ (
    .a(\counter[15] ),
    .b(_060_),
    .c(\counter[16] ),
    .y(_063_)
  );
  xci2_and3 _171_ (
    .a(\counter[16] ),
    .b(\counter[15] ),
    .c(_060_),
    .y(_064_)
  );
  xci2_nor3fft _172_ (
    .a(_092_),
    .b(_063_),
    .c(_064_),
    .y(_007_)
  );
  xci2_xnor2 _173_ (
    .a(\counter[17] ),
    .b(_064_),
    .y(_065_)
  );
  xci2_aoi21 _174_ (
    .a(\counter[25] ),
    .b(_091_),
    .c(_065_),
    .y(_008_)
  );
  xci2_ao21 _175_ (
    .a(\counter[17] ),
    .b(_064_),
    .c(\counter[18] ),
    .y(_066_)
  );
  xci2_and3 _176_ (
    .a(\counter[18] ),
    .b(\counter[17] ),
    .c(_064_),
    .y(_067_)
  );
  xci2_nor3fft _177_ (
    .a(_092_),
    .b(_066_),
    .c(_067_),
    .y(_009_)
  );
  xci2_oai21 _178_ (
    .a(\counter[19] ),
    .b(_067_),
    .c(_092_),
    .y(_068_)
  );
  xci2_aoi21 _179_ (
    .a(\counter[19] ),
    .b(_067_),
    .c(_068_),
    .y(_010_)
  );
  xci2_ao21 _180_ (
    .a(\counter[19] ),
    .b(_067_),
    .c(\counter[20] ),
    .y(_069_)
  );
  xci2_and3 _181_ (
    .a(\counter[19] ),
    .b(\counter[20] ),
    .c(_067_),
    .y(_070_)
  );
  xci2_nor3fft _182_ (
    .a(_092_),
    .b(_069_),
    .c(_070_),
    .y(_012_)
  );
  xci2_aoi21ttf _183_ (
    .a(\counter[21] ),
    .b(_070_),
    .c(_092_),
    .y(_071_)
  );
  xci2_oa21 _184_ (
    .a(\counter[21] ),
    .b(_070_),
    .c(_071_),
    .y(_013_)
  );
  xci2_ao21 _185_ (
    .a(\counter[21] ),
    .b(_070_),
    .c(\counter[22] ),
    .y(_072_)
  );
  xci2_nand3 _186_ (
    .a(\counter[21] ),
    .b(\counter[22] ),
    .c(_070_),
    .y(_073_)
  );
  xci2_and3 _187_ (
    .a(_092_),
    .b(_072_),
    .c(_073_),
    .y(_014_)
  );
  xci2_ao21ftf _188_ (
    .a(\counter[23] ),
    .b(_073_),
    .c(_092_),
    .y(_074_)
  );
  xci2_oa21ftf _189_ (
    .a(\counter[23] ),
    .b(_073_),
    .c(_074_),
    .y(_015_)
  );
  xci2_oai21ftf _190_ (
    .a(\counter[23] ),
    .b(_073_),
    .c(\counter[24] ),
    .y(_075_)
  );
  xci2_or3fft _191_ (
    .a(\counter[24] ),
    .b(\counter[23] ),
    .c(_073_),
    .y(_076_)
  );
  xci2_and3 _192_ (
    .a(_092_),
    .b(_075_),
    .c(_076_),
    .y(_016_)
  );
  xci2_oai21ftt _193_ (
    .a(\counter[23] ),
    .b(_073_),
    .c(_091_),
    .y(_077_)
  );
  xci2_oa21 _194_ (
    .a(\counter[24] ),
    .b(\counter[25] ),
    .c(_092_),
    .y(_078_)
  );
  xci2_and2 _195_ (
    .a(_077_),
    .b(_078_),
    .y(_017_)
  );
  xci2_dffs _196_ (
    .clk(clk),
    .d(_027_),
    .q(led[0]),
    .s(_026_)
  );
  xci2_dffcl _197_ (
    .clk(clk),
    .clr(rst_l),
    .d(_028_),
    .q(led[1])
  );
  xci2_dffcl _198_ (
    .clk(clk),
    .clr(rst_l),
    .d(_029_),
    .q(led[2])
  );
  xci2_dffcl _199_ (
    .clk(clk),
    .clr(rst_l),
    .d(_030_),
    .q(led[3])
  );
  xci2_dffcl _200_ (
    .clk(clk),
    .clr(rst_l),
    .d(_031_),
    .q(led[4])
  );
  xci2_dffcl _201_ (
    .clk(clk),
    .clr(rst_l),
    .d(_032_),
    .q(led[5])
  );
  xci2_dffcl _202_ (
    .clk(clk),
    .clr(rst_l),
    .d(_033_),
    .q(led[6])
  );
  xci2_dffcl _203_ (
    .clk(clk),
    .clr(rst_l),
    .d(_034_),
    .q(led[7])
  );
  xci2_dffcl _204_ (
    .clk(clk),
    .clr(rst_l),
    .d(_035_),
    .q(\current_led[0] )
  );
  xci2_dffcl _205_ (
    .clk(clk),
    .clr(rst_l),
    .d(_036_),
    .q(\current_led[1] )
  );
  xci2_dffcl _206_ (
    .clk(clk),
    .clr(rst_l),
    .d(_037_),
    .q(\current_led[2] )
  );
  xci2_dffcl _207_ (
    .clk(clk),
    .clr(rst_l),
    .d(_000_),
    .q(\counter[0] )
  );
  xci2_dffcl _208_ (
    .clk(clk),
    .clr(rst_l),
    .d(_011_),
    .q(\counter[1] )
  );
  xci2_dffcl _209_ (
    .clk(clk),
    .clr(rst_l),
    .d(_018_),
    .q(\counter[2] )
  );
  xci2_dffcl _210_ (
    .clk(clk),
    .clr(rst_l),
    .d(_019_),
    .q(\counter[3] )
  );
  xci2_dffcl _211_ (
    .clk(clk),
    .clr(rst_l),
    .d(_020_),
    .q(\counter[4] )
  );
  xci2_dffcl _212_ (
    .clk(clk),
    .clr(rst_l),
    .d(_021_),
    .q(\counter[5] )
  );
  xci2_dffcl _213_ (
    .clk(clk),
    .clr(rst_l),
    .d(_022_),
    .q(\counter[6] )
  );
  xci2_dffcl _214_ (
    .clk(clk),
    .clr(rst_l),
    .d(_023_),
    .q(\counter[7] )
  );
  xci2_dffcl _215_ (
    .clk(clk),
    .clr(rst_l),
    .d(_024_),
    .q(\counter[8] )
  );
  xci2_dffcl _216_ (
    .clk(clk),
    .clr(rst_l),
    .d(_025_),
    .q(\counter[9] )
  );
  xci2_dffcl _217_ (
    .clk(clk),
    .clr(rst_l),
    .d(_001_),
    .q(\counter[10] )
  );
  xci2_dffcl _218_ (
    .clk(clk),
    .clr(rst_l),
    .d(_002_),
    .q(\counter[11] )
  );
  xci2_dffcl _219_ (
    .clk(clk),
    .clr(rst_l),
    .d(_003_),
    .q(\counter[12] )
  );
  xci2_dffcl _220_ (
    .clk(clk),
    .clr(rst_l),
    .d(_004_),
    .q(\counter[13] )
  );
  xci2_dffcl _221_ (
    .clk(clk),
    .clr(rst_l),
    .d(_005_),
    .q(\counter[14] )
  );
  xci2_dffcl _222_ (
    .clk(clk),
    .clr(rst_l),
    .d(_006_),
    .q(\counter[15] )
  );
  xci2_dffcl _223_ (
    .clk(clk),
    .clr(rst_l),
    .d(_007_),
    .q(\counter[16] )
  );
  xci2_dffcl _224_ (
    .clk(clk),
    .clr(rst_l),
    .d(_008_),
    .q(\counter[17] )
  );
  xci2_dffcl _225_ (
    .clk(clk),
    .clr(rst_l),
    .d(_009_),
    .q(\counter[18] )
  );
  xci2_dffcl _226_ (
    .clk(clk),
    .clr(rst_l),
    .d(_010_),
    .q(\counter[19] )
  );
  xci2_dffcl _227_ (
    .clk(clk),
    .clr(rst_l),
    .d(_012_),
    .q(\counter[20] )
  );
  xci2_dffcl _228_ (
    .clk(clk),
    .clr(rst_l),
    .d(_013_),
    .q(\counter[21] )
  );
  xci2_dffcl _229_ (
    .clk(clk),
    .clr(rst_l),
    .d(_014_),
    .q(\counter[22] )
  );
  xci2_dffcl _230_ (
    .clk(clk),
    .clr(rst_l),
    .d(_015_),
    .q(\counter[23] )
  );
  xci2_dffcl _231_ (
    .clk(clk),
    .clr(rst_l),
    .d(_016_),
    .q(\counter[24] )
  );
  xci2_dffcl _232_ (
    .clk(clk),
    .clr(rst_l),
    .d(_017_),
    .q(\counter[25] )
  );
endmodule
