/* Generated by Yosys 0.36+58 (git sha1 ea7818d31, x86_64-w64-mingw32-g++ 13.2.0 -O3 -DNDEBUG) */

module test(key, clk, hex0, led);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  input clk;
  wire clk;
  wire \counter[0] ;
  wire \counter[10] ;
  wire \counter[11] ;
  wire \counter[12] ;
  wire \counter[13] ;
  wire \counter[14] ;
  wire \counter[15] ;
  wire \counter[16] ;
  wire \counter[17] ;
  wire \counter[18] ;
  wire \counter[19] ;
  wire \counter[1] ;
  wire \counter[20] ;
  wire \counter[21] ;
  wire \counter[22] ;
  wire \counter[23] ;
  wire \counter[24] ;
  wire \counter[25] ;
  wire \counter[2] ;
  wire \counter[3] ;
  wire \counter[4] ;
  wire \counter[5] ;
  wire \counter[6] ;
  wire \counter[7] ;
  wire \counter[8] ;
  wire \counter[9] ;
  output [7:0] hex0;
  wire [7:0] hex0;
  input key;
  wire key;
  output [7:0] led;
  wire [7:0] led;
  wire \num[0] ;
  wire \num[1] ;
  wire \num[2] ;
  wire \num[3] ;
  xci2_nor2 _143_ (
    .a(\counter[21] ),
    .b(\counter[22] ),
    .y(_129_)
  );
  xci2_and3fft _144_ (
    .a(\counter[24] ),
    .b(\counter[25] ),
    .c(_129_),
    .y(_130_)
  );
  xci2_nor2 _145_ (
    .a(\counter[14] ),
    .b(\counter[16] ),
    .y(_131_)
  );
  xci2_and3fft _146_ (
    .a(\counter[17] ),
    .b(\counter[18] ),
    .c(_131_),
    .y(_132_)
  );
  xci2_nor2 _147_ (
    .a(\counter[6] ),
    .b(\counter[8] ),
    .y(_133_)
  );
  xci2_and3fft _148_ (
    .a(\counter[11] ),
    .b(\counter[13] ),
    .c(_133_),
    .y(_134_)
  );
  xci2_and3 _149_ (
    .a(_130_),
    .b(_132_),
    .c(_134_),
    .y(_135_)
  );
  xci2_and2 _150_ (
    .a(\counter[9] ),
    .b(\counter[10] ),
    .y(_136_)
  );
  xci2_and2 _151_ (
    .a(\counter[19] ),
    .b(\counter[20] ),
    .y(_137_)
  );
  xci2_nor2 _152_ (
    .a(\counter[0] ),
    .b(\counter[1] ),
    .y(_138_)
  );
  xci2_and3 _153_ (
    .a(_136_),
    .b(_137_),
    .c(_138_),
    .y(_139_)
  );
  xci2_nor2 _154_ (
    .a(\counter[2] ),
    .b(\counter[3] ),
    .y(_140_)
  );
  xci2_and3fft _155_ (
    .a(\counter[4] ),
    .b(\counter[5] ),
    .c(_140_),
    .y(_141_)
  );
  xci2_and2 _156_ (
    .a(\counter[15] ),
    .b(\counter[23] ),
    .y(_142_)
  );
  xci2_and3 _157_ (
    .a(\counter[7] ),
    .b(\counter[12] ),
    .c(_142_),
    .y(_038_)
  );
  xci2_and3 _158_ (
    .a(_139_),
    .b(_141_),
    .c(_038_),
    .y(_039_)
  );
  xci2_and2 _159_ (
    .a(_135_),
    .b(_039_),
    .y(_040_)
  );
  xci2_nand3ftt _160_ (
    .a(\counter[4] ),
    .b(_131_),
    .c(\counter[7] ),
    .y(_041_)
  );
  xci2_and3fft _161_ (
    .a(_041_),
    .b(\counter[2] ),
    .c(_137_),
    .y(_042_)
  );
  xci2_and3fft _162_ (
    .a(\counter[13] ),
    .b(\counter[18] ),
    .c(_136_),
    .y(_043_)
  );
  xci2_and3fft _163_ (
    .a(\counter[3] ),
    .b(\counter[22] ),
    .c(_043_),
    .y(_044_)
  );
  xci2_nor3 _164_ (
    .a(\counter[6] ),
    .b(\counter[11] ),
    .c(\counter[25] ),
    .y(_045_)
  );
  xci2_or2 _165_ (
    .a(\counter[21] ),
    .b(\counter[24] ),
    .y(_046_)
  );
  xci2_and3fft _166_ (
    .a(\counter[8] ),
    .b(_046_),
    .c(\counter[12] ),
    .y(_047_)
  );
  xci2_nand3ftt _167_ (
    .a(\counter[17] ),
    .b(\counter[23] ),
    .c(\counter[15] ),
    .y(_048_)
  );
  xci2_and3fft _168_ (
    .a(_048_),
    .b(\counter[5] ),
    .c(_138_),
    .y(_049_)
  );
  xci2_and3 _169_ (
    .a(_045_),
    .b(_047_),
    .c(_049_),
    .y(_050_)
  );
  xci2_nand3 _170_ (
    .a(_042_),
    .b(_044_),
    .c(_050_),
    .y(_051_)
  );
  xci2_and2ft _171_ (
    .a(_040_),
    .b(key),
    .y(_052_)
  );
  xci2_and3ftt _172_ (
    .a(\counter[0] ),
    .b(_051_),
    .c(key),
    .y(_000_)
  );
  xci2_xnor2ft _173_ (
    .a(\counter[0] ),
    .b(\counter[1] ),
    .y(_053_)
  );
  xci2_and3 _174_ (
    .a(key),
    .b(_051_),
    .c(_053_),
    .y(_001_)
  );
  xci2_aoi21 _175_ (
    .a(\counter[0] ),
    .b(\counter[1] ),
    .c(\counter[2] ),
    .y(_054_)
  );
  xci2_and3 _176_ (
    .a(\counter[0] ),
    .b(\counter[1] ),
    .c(\counter[2] ),
    .y(_055_)
  );
  xci2_and3fft _177_ (
    .a(_054_),
    .b(_055_),
    .c(_052_),
    .y(_002_)
  );
  xci2_xnor2ft _178_ (
    .a(\counter[3] ),
    .b(_055_),
    .y(_056_)
  );
  xci2_and3 _179_ (
    .a(key),
    .b(_051_),
    .c(_056_),
    .y(_003_)
  );
  xci2_aoi21 _180_ (
    .a(\counter[3] ),
    .b(_055_),
    .c(\counter[4] ),
    .y(_057_)
  );
  xci2_and3 _181_ (
    .a(\counter[3] ),
    .b(\counter[4] ),
    .c(_055_),
    .y(_058_)
  );
  xci2_and3fft _182_ (
    .a(_057_),
    .b(_058_),
    .c(_052_),
    .y(_004_)
  );
  xci2_xnor2ft _183_ (
    .a(\counter[5] ),
    .b(_058_),
    .y(_059_)
  );
  xci2_and3 _184_ (
    .a(key),
    .b(_051_),
    .c(_059_),
    .y(_005_)
  );
  xci2_and3 _185_ (
    .a(\counter[5] ),
    .b(\counter[6] ),
    .c(_058_),
    .y(_060_)
  );
  xci2_aoi21 _186_ (
    .a(\counter[5] ),
    .b(_058_),
    .c(\counter[6] ),
    .y(_061_)
  );
  xci2_and3fft _187_ (
    .a(_060_),
    .b(_061_),
    .c(_052_),
    .y(_006_)
  );
  xci2_oai21 _188_ (
    .a(\counter[7] ),
    .b(_060_),
    .c(_052_),
    .y(_062_)
  );
  xci2_aoi21 _189_ (
    .a(\counter[7] ),
    .b(_060_),
    .c(_062_),
    .y(_007_)
  );
  xci2_and3 _190_ (
    .a(\counter[7] ),
    .b(\counter[8] ),
    .c(_060_),
    .y(_063_)
  );
  xci2_aoi21 _191_ (
    .a(\counter[7] ),
    .b(_060_),
    .c(\counter[8] ),
    .y(_064_)
  );
  xci2_and3fft _192_ (
    .a(_063_),
    .b(_064_),
    .c(_052_),
    .y(_008_)
  );
  xci2_oai21 _193_ (
    .a(\counter[9] ),
    .b(_063_),
    .c(_052_),
    .y(_065_)
  );
  xci2_aoi21 _194_ (
    .a(\counter[9] ),
    .b(_063_),
    .c(_065_),
    .y(_009_)
  );
  xci2_ao21 _195_ (
    .a(\counter[9] ),
    .b(_063_),
    .c(\counter[10] ),
    .y(_066_)
  );
  xci2_nand2 _196_ (
    .a(_136_),
    .b(_063_),
    .y(_067_)
  );
  xci2_and3 _197_ (
    .a(_052_),
    .b(_066_),
    .c(_067_),
    .y(_010_)
  );
  xci2_aoi21 _198_ (
    .a(_136_),
    .b(_063_),
    .c(\counter[11] ),
    .y(_068_)
  );
  xci2_and3 _199_ (
    .a(\counter[11] ),
    .b(_136_),
    .c(_063_),
    .y(_069_)
  );
  xci2_and3fft _200_ (
    .a(_068_),
    .b(_069_),
    .c(_052_),
    .y(_011_)
  );
  xci2_oai21 _201_ (
    .a(\counter[12] ),
    .b(_069_),
    .c(_052_),
    .y(_070_)
  );
  xci2_aoi21 _202_ (
    .a(\counter[12] ),
    .b(_069_),
    .c(_070_),
    .y(_012_)
  );
  xci2_aoi21 _203_ (
    .a(\counter[12] ),
    .b(_069_),
    .c(\counter[13] ),
    .y(_071_)
  );
  xci2_and3 _204_ (
    .a(\counter[12] ),
    .b(\counter[13] ),
    .c(_069_),
    .y(_072_)
  );
  xci2_and3fft _205_ (
    .a(_071_),
    .b(_072_),
    .c(_052_),
    .y(_013_)
  );
  xci2_oai21 _206_ (
    .a(\counter[14] ),
    .b(_072_),
    .c(_052_),
    .y(_073_)
  );
  xci2_aoi21 _207_ (
    .a(\counter[14] ),
    .b(_072_),
    .c(_073_),
    .y(_014_)
  );
  xci2_aoi21 _208_ (
    .a(\counter[14] ),
    .b(_072_),
    .c(\counter[15] ),
    .y(_074_)
  );
  xci2_and3 _209_ (
    .a(\counter[15] ),
    .b(\counter[14] ),
    .c(_072_),
    .y(_075_)
  );
  xci2_and3fft _210_ (
    .a(_074_),
    .b(_075_),
    .c(_052_),
    .y(_015_)
  );
  xci2_oai21 _211_ (
    .a(\counter[16] ),
    .b(_075_),
    .c(_052_),
    .y(_076_)
  );
  xci2_aoi21 _212_ (
    .a(\counter[16] ),
    .b(_075_),
    .c(_076_),
    .y(_016_)
  );
  xci2_aoi21 _213_ (
    .a(\counter[16] ),
    .b(_075_),
    .c(\counter[17] ),
    .y(_077_)
  );
  xci2_and3 _214_ (
    .a(\counter[16] ),
    .b(\counter[17] ),
    .c(_075_),
    .y(_078_)
  );
  xci2_and3fft _215_ (
    .a(_077_),
    .b(_078_),
    .c(_052_),
    .y(_017_)
  );
  xci2_oa21 _216_ (
    .a(\counter[18] ),
    .b(_078_),
    .c(_052_),
    .y(_079_)
  );
  xci2_and2 _217_ (
    .a(\counter[18] ),
    .b(_078_),
    .y(_080_)
  );
  xci2_and2ft _218_ (
    .a(_080_),
    .b(_079_),
    .y(_018_)
  );
  xci2_oai21 _219_ (
    .a(\counter[19] ),
    .b(_080_),
    .c(_052_),
    .y(_081_)
  );
  xci2_aoi21 _220_ (
    .a(\counter[19] ),
    .b(_080_),
    .c(_081_),
    .y(_019_)
  );
  xci2_ao21 _221_ (
    .a(\counter[19] ),
    .b(_080_),
    .c(\counter[20] ),
    .y(_082_)
  );
  xci2_and3 _222_ (
    .a(\counter[18] ),
    .b(_137_),
    .c(_078_),
    .y(_083_)
  );
  xci2_nand3 _223_ (
    .a(\counter[18] ),
    .b(_137_),
    .c(_078_),
    .y(_084_)
  );
  xci2_and3 _224_ (
    .a(_052_),
    .b(_082_),
    .c(_084_),
    .y(_020_)
  );
  xci2_aoi21ttf _225_ (
    .a(\counter[21] ),
    .b(_083_),
    .c(_052_),
    .y(_085_)
  );
  xci2_aoi21ftf _226_ (
    .a(\counter[21] ),
    .b(_084_),
    .c(_085_),
    .y(_021_)
  );
  xci2_aoi21 _227_ (
    .a(\counter[21] ),
    .b(_083_),
    .c(\counter[22] ),
    .y(_086_)
  );
  xci2_and3 _228_ (
    .a(\counter[21] ),
    .b(\counter[22] ),
    .c(_083_),
    .y(_087_)
  );
  xci2_and3fft _229_ (
    .a(_086_),
    .b(_087_),
    .c(_052_),
    .y(_022_)
  );
  xci2_oai21 _230_ (
    .a(\counter[23] ),
    .b(_087_),
    .c(_052_),
    .y(_088_)
  );
  xci2_aoi21 _231_ (
    .a(\counter[23] ),
    .b(_087_),
    .c(_088_),
    .y(_023_)
  );
  xci2_ao21 _232_ (
    .a(\counter[23] ),
    .b(_087_),
    .c(\counter[24] ),
    .y(_089_)
  );
  xci2_nand3 _233_ (
    .a(\counter[23] ),
    .b(\counter[24] ),
    .c(_087_),
    .y(_090_)
  );
  xci2_and3 _234_ (
    .a(_052_),
    .b(_089_),
    .c(_090_),
    .y(_024_)
  );
  xci2_xnor2 _235_ (
    .a(\counter[25] ),
    .b(_090_),
    .y(_091_)
  );
  xci2_and2 _236_ (
    .a(_052_),
    .b(_091_),
    .y(_025_)
  );
  xci2_aoi21ftf _237_ (
    .a(led[0]),
    .b(_051_),
    .c(key),
    .y(_092_)
  );
  xci2_or2ft _238_ (
    .a(led[0]),
    .b(_051_),
    .y(_093_)
  );
  xci2_and2 _239_ (
    .a(_092_),
    .b(_093_),
    .y(_026_)
  );
  xci2_aoi21ftf _240_ (
    .a(led[1]),
    .b(_093_),
    .c(key),
    .y(_094_)
  );
  xci2_and3 _241_ (
    .a(led[0]),
    .b(led[1]),
    .c(_040_),
    .y(_095_)
  );
  xci2_nand2 _242_ (
    .a(led[0]),
    .b(led[1]),
    .y(_096_)
  );
  xci2_and2ft _243_ (
    .a(_095_),
    .b(_094_),
    .y(_027_)
  );
  xci2_or2 _244_ (
    .a(led[2]),
    .b(_095_),
    .y(_097_)
  );
  xci2_or3ftt _245_ (
    .a(led[2]),
    .b(_051_),
    .c(_096_),
    .y(_098_)
  );
  xci2_and3 _246_ (
    .a(key),
    .b(_097_),
    .c(_098_),
    .y(_028_)
  );
  xci2_aoi21ftf _247_ (
    .a(led[3]),
    .b(_098_),
    .c(key),
    .y(_099_)
  );
  xci2_nand3 _248_ (
    .a(led[2]),
    .b(led[3]),
    .c(_095_),
    .y(_100_)
  );
  xci2_and2 _249_ (
    .a(_099_),
    .b(_100_),
    .y(_029_)
  );
  xci2_aoi21ftf _250_ (
    .a(led[4]),
    .b(_100_),
    .c(key),
    .y(_101_)
  );
  xci2_or2ft _251_ (
    .a(led[4]),
    .b(_100_),
    .y(_102_)
  );
  xci2_and2 _252_ (
    .a(_101_),
    .b(_102_),
    .y(_030_)
  );
  xci2_aoi21ftf _253_ (
    .a(led[5]),
    .b(_102_),
    .c(key),
    .y(_103_)
  );
  xci2_or3fft _254_ (
    .a(led[4]),
    .b(led[5]),
    .c(_100_),
    .y(_104_)
  );
  xci2_and2 _255_ (
    .a(_103_),
    .b(_104_),
    .y(_031_)
  );
  xci2_aoi21ftf _256_ (
    .a(led[6]),
    .b(_104_),
    .c(key),
    .y(_105_)
  );
  xci2_nor2ft _257_ (
    .a(led[6]),
    .b(_104_),
    .y(_106_)
  );
  xci2_and2ft _258_ (
    .a(_106_),
    .b(_105_),
    .y(_032_)
  );
  xci2_xnor2 _259_ (
    .a(led[7]),
    .b(_106_),
    .y(_107_)
  );
  xci2_and2ft _260_ (
    .a(_107_),
    .b(key),
    .y(_033_)
  );
  xci2_xnor2 _261_ (
    .a(\num[0] ),
    .b(_051_),
    .y(_108_)
  );
  xci2_and2 _262_ (
    .a(key),
    .b(_108_),
    .y(_034_)
  );
  xci2_nand3fft _263_ (
    .a(\num[0] ),
    .b(\num[2] ),
    .c(\num[1] ),
    .y(_109_)
  );
  xci2_oa21ftt _264_ (
    .a(\num[3] ),
    .b(_109_),
    .c(\num[1] ),
    .y(_110_)
  );
  xci2_xnor2ft _265_ (
    .a(\num[0] ),
    .b(\num[1] ),
    .y(_111_)
  );
  xci2_mux2h _266_ (
    .a(_110_),
    .b(_111_),
    .s(_040_),
    .y(_112_)
  );
  xci2_and2 _267_ (
    .a(key),
    .b(_112_),
    .y(_035_)
  );
  xci2_or3fft _268_ (
    .a(\num[0] ),
    .b(\num[1] ),
    .c(_051_),
    .y(_113_)
  );
  xci2_and3 _269_ (
    .a(\num[0] ),
    .b(\num[1] ),
    .c(\num[2] ),
    .y(_114_)
  );
  xci2_aoi21ftf _270_ (
    .a(_051_),
    .b(_114_),
    .c(key),
    .y(_115_)
  );
  xci2_aoi21ftf _271_ (
    .a(\num[2] ),
    .b(_113_),
    .c(_115_),
    .y(_036_)
  );
  xci2_and3 _272_ (
    .a(\num[3] ),
    .b(_051_),
    .c(_109_),
    .y(_116_)
  );
  xci2_nand2ft _273_ (
    .a(\num[3] ),
    .b(\num[2] ),
    .y(_117_)
  );
  xci2_nand2ft _274_ (
    .a(\num[3] ),
    .b(_114_),
    .y(hex0[0])
  );
  xci2_xnor2ft _275_ (
    .a(\num[3] ),
    .b(_114_),
    .y(_118_)
  );
  xci2_nand2ft _276_ (
    .a(_051_),
    .b(_118_),
    .y(_119_)
  );
  xci2_aoi21ftf _277_ (
    .a(_116_),
    .b(_119_),
    .c(key),
    .y(_037_)
  );
  xci2_or2 _278_ (
    .a(\num[1] ),
    .b(\num[2] ),
    .y(_120_)
  );
  xci2_ao21ftt _279_ (
    .a(_114_),
    .b(_120_),
    .c(\num[3] ),
    .y(hex0[1])
  );
  xci2_ao21ttf _280_ (
    .a(\num[0] ),
    .b(\num[1] ),
    .c(\num[2] ),
    .y(_121_)
  );
  xci2_oai21ttf _281_ (
    .a(\num[0] ),
    .b(\num[1] ),
    .c(\num[3] ),
    .y(_122_)
  );
  xci2_mux2h _282_ (
    .a(\num[2] ),
    .b(_117_),
    .s(\num[1] ),
    .y(_123_)
  );
  xci2_ao21ftt _283_ (
    .a(\num[3] ),
    .b(\num[0] ),
    .c(_123_),
    .y(_124_)
  );
  xci2_oai21 _284_ (
    .a(\num[1] ),
    .b(\num[2] ),
    .c(\num[3] ),
    .y(_125_)
  );
  xci2_nand2ft _285_ (
    .a(_122_),
    .b(_121_),
    .y(hex0[2])
  );
  xci2_ao21ftt _286_ (
    .a(\num[1] ),
    .b(\num[2] ),
    .c(\num[0] ),
    .y(_126_)
  );
  xci2_nand2 _287_ (
    .a(_125_),
    .b(_126_),
    .y(hex0[3])
  );
  xci2_xnor2ft _288_ (
    .a(\num[1] ),
    .b(\num[2] ),
    .y(_127_)
  );
  xci2_aoi21ftf _289_ (
    .a(_122_),
    .b(_127_),
    .c(_124_),
    .y(_128_)
  );
  xci2_nand2 _290_ (
    .a(_125_),
    .b(_128_),
    .y(hex0[4])
  );
  xci2_or2 _291_ (
    .a(\num[3] ),
    .b(_109_),
    .y(hex0[5])
  );
  xci2_or2ft _292_ (
    .a(_111_),
    .b(_117_),
    .y(hex0[6])
  );
  xci2_nand2 _293_ (
    .a(hex0[0]),
    .b(_128_),
    .y(hex0[7])
  );
  xci2_dff _294_ (
    .clk(clk),
    .d(_000_),
    .q(\counter[0] )
  );
  xci2_dff _295_ (
    .clk(clk),
    .d(_001_),
    .q(\counter[1] )
  );
  xci2_dff _296_ (
    .clk(clk),
    .d(_002_),
    .q(\counter[2] )
  );
  xci2_dff _297_ (
    .clk(clk),
    .d(_003_),
    .q(\counter[3] )
  );
  xci2_dff _298_ (
    .clk(clk),
    .d(_004_),
    .q(\counter[4] )
  );
  xci2_dff _299_ (
    .clk(clk),
    .d(_005_),
    .q(\counter[5] )
  );
  xci2_dff _300_ (
    .clk(clk),
    .d(_006_),
    .q(\counter[6] )
  );
  xci2_dff _301_ (
    .clk(clk),
    .d(_007_),
    .q(\counter[7] )
  );
  xci2_dff _302_ (
    .clk(clk),
    .d(_008_),
    .q(\counter[8] )
  );
  xci2_dff _303_ (
    .clk(clk),
    .d(_009_),
    .q(\counter[9] )
  );
  xci2_dff _304_ (
    .clk(clk),
    .d(_010_),
    .q(\counter[10] )
  );
  xci2_dff _305_ (
    .clk(clk),
    .d(_011_),
    .q(\counter[11] )
  );
  xci2_dff _306_ (
    .clk(clk),
    .d(_012_),
    .q(\counter[12] )
  );
  xci2_dff _307_ (
    .clk(clk),
    .d(_013_),
    .q(\counter[13] )
  );
  xci2_dff _308_ (
    .clk(clk),
    .d(_014_),
    .q(\counter[14] )
  );
  xci2_dff _309_ (
    .clk(clk),
    .d(_015_),
    .q(\counter[15] )
  );
  xci2_dff _310_ (
    .clk(clk),
    .d(_016_),
    .q(\counter[16] )
  );
  xci2_dff _311_ (
    .clk(clk),
    .d(_017_),
    .q(\counter[17] )
  );
  xci2_dff _312_ (
    .clk(clk),
    .d(_018_),
    .q(\counter[18] )
  );
  xci2_dff _313_ (
    .clk(clk),
    .d(_019_),
    .q(\counter[19] )
  );
  xci2_dff _314_ (
    .clk(clk),
    .d(_020_),
    .q(\counter[20] )
  );
  xci2_dff _315_ (
    .clk(clk),
    .d(_021_),
    .q(\counter[21] )
  );
  xci2_dff _316_ (
    .clk(clk),
    .d(_022_),
    .q(\counter[22] )
  );
  xci2_dff _317_ (
    .clk(clk),
    .d(_023_),
    .q(\counter[23] )
  );
  xci2_dff _318_ (
    .clk(clk),
    .d(_024_),
    .q(\counter[24] )
  );
  xci2_dff _319_ (
    .clk(clk),
    .d(_025_),
    .q(\counter[25] )
  );
  xci2_dff _320_ (
    .clk(clk),
    .d(_026_),
    .q(led[0])
  );
  xci2_dff _321_ (
    .clk(clk),
    .d(_027_),
    .q(led[1])
  );
  xci2_dff _322_ (
    .clk(clk),
    .d(_028_),
    .q(led[2])
  );
  xci2_dff _323_ (
    .clk(clk),
    .d(_029_),
    .q(led[3])
  );
  xci2_dff _324_ (
    .clk(clk),
    .d(_030_),
    .q(led[4])
  );
  xci2_dff _325_ (
    .clk(clk),
    .d(_031_),
    .q(led[5])
  );
  xci2_dff _326_ (
    .clk(clk),
    .d(_032_),
    .q(led[6])
  );
  xci2_dff _327_ (
    .clk(clk),
    .d(_033_),
    .q(led[7])
  );
  xci2_dff _328_ (
    .clk(clk),
    .d(_034_),
    .q(\num[0] )
  );
  xci2_dff _329_ (
    .clk(clk),
    .d(_035_),
    .q(\num[1] )
  );
  xci2_dff _330_ (
    .clk(clk),
    .d(_036_),
    .q(\num[2] )
  );
  xci2_dff _331_ (
    .clk(clk),
    .d(_037_),
    .q(\num[3] )
  );
endmodule
